// Tag descriptions utility
export const tagDescriptions: Record<string, string> = {
  'Family': 'You will live with a family in their home',
  'Women Only': 'This accommodation is exclusively for women',
  'Pets Allowed': 'Pets are welcome in this accommodation',
  'Dogs': 'You will live with dogs in this house',
  'Cats': 'You will live with cats in this house',
  // Lowercase variants used by the upload form (petTypes)
  'dogs': 'You will live with dogs in this house',
  'cats': 'You will live with cats in this house',
  'women-only': 'This accommodation is exclusively for women',
  'live-with-family': 'You will live with a family in their home',
  'pets-allowed': 'Pets are welcome in this accommodation',
  'dogs-allowed': 'You will live with dogs in this house',
  'cats-allowed': 'You will live with cats in this house',
  'Pets': 'Pets are welcome in this accommodation',
  'Pet Friendly': 'This accommodation is pet-friendly',
  'No Pets': 'No pets are allowed in this accommodation',
  'Male Only': 'This accommodation is exclusively for men',
  'Mixed Gender': 'This accommodation welcomes all genders',
  'Students Only': 'This accommodation is exclusively for students',
  'Professionals Only': 'This accommodation is exclusively for working professionals',
  'Quiet': 'This is a quiet accommodation suitable for study or work',
  'Social': 'This accommodation encourages social interaction',
  'Private': 'This accommodation offers private spaces',
  'Shared': 'This accommodation has shared common areas',
  'Furnished': 'This accommodation comes fully furnished',
  'Unfurnished': 'This accommodation is unfurnished',
  'Utilities Included': 'Utilities are included in the rent',
  'Utilities Not Included': 'Utilities are not included in the rent',
  'Near University': 'This accommodation is located near a university',
  'Near City Center': 'This accommodation is located near the city center',
  'Near Public Transport': 'This accommodation is near public transportation',
  'Parking Available': 'Parking is available at this accommodation',
  'Garden': 'This accommodation has a garden',
  'Balcony': 'This accommodation has a balcony',
  'Terrace': 'This accommodation has a terrace',
  'Pool': 'This accommodation has a swimming pool',
  'Gym': 'This accommodation has a gym facility',
  'Laundry': 'Laundry facilities are available',
  'WiFi': 'High-speed WiFi is available',
  'Air Conditioning': 'Air conditioning is available',
  'Heating': 'Heating is available',
  'Kitchen': 'Kitchen facilities are available',
  'Dishwasher': 'Dishwasher is available',
  'Washing Machine': 'Washing machine is available',
  'Dryer': 'Clothes dryer is available',
  'Microwave': 'Microwave is available',
  'Refrigerator': 'Refrigerator is available',
  'Oven': 'Oven is available',
  'Stove': 'Stove is available',
  'Dining Area': 'Dining area is available',
  'Living Room': 'Living room is available',
  'Study Area': 'Study area is available',
  'Storage': 'Storage space is available',
  'Security': 'Security measures are in place',
  'CCTV': 'CCTV surveillance is available',
  'Intercom': 'Intercom system is available',
  'Elevator': 'Elevator is available',
  'Wheelchair Accessible': 'This accommodation is wheelchair accessible',
  'Smoking Allowed': 'Smoking is allowed in this accommodation',
  'No Smoking': 'Smoking is not allowed in this accommodation',
  'Alcohol Allowed': 'Alcohol consumption is allowed',
  'No Alcohol': 'Alcohol consumption is not allowed',
  'Parties Allowed': 'Parties are allowed in this accommodation',
  'No Parties': 'Parties are not allowed in this accommodation',
  'Visitors Allowed': 'Visitors are welcome',
  'No Visitors': 'Visitors are not allowed',
  'Couples Welcome': 'Couples are welcome',
  'No Couples': 'Couples are not allowed',
  'Children Welcome': 'Children are welcome',
  'No Children': 'Children are not allowed',
  'Elderly Friendly': 'This accommodation is suitable for elderly residents',
  'International Students': 'This accommodation welcomes international students',
  'Local Students': 'This accommodation is for local students',
  'Exchange Students': 'This accommodation is for exchange students',
  'Graduate Students': 'This accommodation is for graduate students',
  'Undergraduate Students': 'This accommodation is for undergraduate students',
  'PhD Students': 'This accommodation is for PhD students',
  'Postdoc': 'This accommodation is for postdoctoral researchers',
  'Researchers': 'This accommodation is for researchers',
  'Faculty': 'This accommodation is for faculty members',
  'Staff': 'This accommodation is for university staff',
  'Interns': 'This accommodation is for interns',
  'Trainees': 'This accommodation is for trainees',
  'Apprentices': 'This accommodation is for apprentices',
  'Volunteers': 'This accommodation is for volunteers',
  'Tourists': 'This accommodation is for tourists',
  'Business Travelers': 'This accommodation is for business travelers',
  'Digital Nomads': 'This accommodation is for digital nomads',
  'Remote Workers': 'This accommodation is for remote workers',
  'Freelancers': 'This accommodation is for freelancers',
  'Entrepreneurs': 'This accommodation is for entrepreneurs',
  'Startup Founders': 'This accommodation is for startup founders',
  'Investors': 'This accommodation is for investors',
  'Consultants': 'This accommodation is for consultants',
  'Contractors': 'This accommodation is for contractors',
  'Temporary Workers': 'This accommodation is for temporary workers',
  'Seasonal Workers': 'This accommodation is for seasonal workers',
  'Migrant Workers': 'This accommodation is for migrant workers',
  'Refugees': 'This accommodation is for refugees',
  'Asylum Seekers': 'This accommodation is for asylum seekers',
  'Immigrants': 'This accommodation is for immigrants',
  'Expats': 'This accommodation is for expatriates',
  'Diplomats': 'This accommodation is for diplomats',
  'Government Officials': 'This accommodation is for government officials',
  'Military Personnel': 'This accommodation is for military personnel',
  'Veterans': 'This accommodation is for veterans',
  'First Responders': 'This accommodation is for first responders',
  'Healthcare Workers': 'This accommodation is for healthcare workers',
  'Teachers': 'This accommodation is for teachers',
  'Nurses': 'This accommodation is for nurses',
  'Doctors': 'This accommodation is for doctors',
  'Engineers': 'This accommodation is for engineers',
  'Architects': 'This accommodation is for architects',
  'Lawyers': 'This accommodation is for lawyers',
  'Accountants': 'This accommodation is for accountants',
  'Bankers': 'This accommodation is for bankers',
  'Insurance Agents': 'This accommodation is for insurance agents',
  'Real Estate Agents': 'This accommodation is for real estate agents',
  'Sales Representatives': 'This accommodation is for sales representatives',
  'Marketing Professionals': 'This accommodation is for marketing professionals',
  'Designers': 'This accommodation is for designers',
  'Artists': 'This accommodation is for artists',
  'Musicians': 'This accommodation is for musicians',
  'Writers': 'This accommodation is for writers',
  'Journalists': 'This accommodation is for journalists',
  'Photographers': 'This accommodation is for photographers',
  'Videographers': 'This accommodation is for videographers',
  'Filmmakers': 'This accommodation is for filmmakers',
  'Actors': 'This accommodation is for actors',
  'Dancers': 'This accommodation is for dancers',
  'Chefs': 'This accommodation is for chefs',
  'Cooks': 'This accommodation is for cooks',
  'Waiters': 'This accommodation is for waiters',
  'Bartenders': 'This accommodation is for bartenders',
  'Retail Workers': 'This accommodation is for retail workers',
  'Customer Service': 'This accommodation is for customer service representatives',
  'Administrative Staff': 'This accommodation is for administrative staff',
  'Receptionists': 'This accommodation is for receptionists',
  'Secretaries': 'This accommodation is for secretaries',
  'Assistants': 'This accommodation is for assistants',
  'Managers': 'This accommodation is for managers',
  'Supervisors': 'This accommodation is for supervisors',
  'Directors': 'This accommodation is for directors',
  'Executives': 'This accommodation is for executives',
  'CEOs': 'This accommodation is for CEOs',
  'CFOs': 'This accommodation is for CFOs',
  'CTOs': 'This accommodation is for CTOs',
  'COOs': 'This accommodation is for COOs',
  'Presidents': 'This accommodation is for presidents',
  'Vice Presidents': 'This accommodation is for vice presidents',
  'Board Members': 'This accommodation is for board members',
  'Shareholders': 'This accommodation is for shareholders',
  'Stakeholders': 'This accommodation is for stakeholders',
  'Partners': 'This accommodation is for partners',
  'Associates': 'This accommodation is for associates',
  'Senior Associates': 'This accommodation is for senior associates',
  'Junior Associates': 'This accommodation is for junior associates',
  // removed duplicates of roles listed earlier
  'Retirees': 'This accommodation is for retirees',
  'Pensioners': 'This accommodation is for pensioners',
  'Seniors': 'This accommodation is for seniors',
  'Adults': 'This accommodation is for adults',
  'Young Adults': 'This accommodation is for young adults',
  'Teenagers': 'This accommodation is for teenagers',
  'Children': 'This accommodation is for children',
  'Infants': 'This accommodation is for infants',
  'Toddlers': 'This accommodation is for toddlers',
  'Babies': 'This accommodation is for babies',
  'Newborns': 'This accommodation is for newborns',
  'Pregnant Women': 'This accommodation is for pregnant women',
  'New Mothers': 'This accommodation is for new mothers',
  'Single Parents': 'This accommodation is for single parents',
  'Divorced': 'This accommodation is for divorced individuals',
  'Widowed': 'This accommodation is for widowed individuals',
  'Separated': 'This accommodation is for separated individuals',
  'Married': 'This accommodation is for married individuals',
  'Engaged': 'This accommodation is for engaged individuals',
  'Dating': 'This accommodation is for individuals who are dating',
  'Single': 'This accommodation is for single individuals',
  'LGBTQ+': 'This accommodation is LGBTQ+ friendly',
  'Straight': 'This accommodation is for straight individuals',
  'Gay': 'This accommodation is for gay individuals',
  'Lesbian': 'This accommodation is for lesbian individuals',
  'Bisexual': 'This accommodation is for bisexual individuals',
  'Transgender': 'This accommodation is for transgender individuals',
  'Non-binary': 'This accommodation is for non-binary individuals',
  'Queer': 'This accommodation is for queer individuals',
  'Asexual': 'This accommodation is for asexual individuals',
  'Pansexual': 'This accommodation is for pansexual individuals',
  'Demisexual': 'This accommodation is for demisexual individuals',
  'Polyamorous': 'This accommodation is for polyamorous individuals',
  'Monogamous': 'This accommodation is for monogamous individuals',
  'Open Relationship': 'This accommodation is for individuals in open relationships',
  'Closed Relationship': 'This accommodation is for individuals in closed relationships',
  'Long Distance': 'This accommodation is for individuals in long distance relationships',
  'Local': 'This accommodation is for local individuals',
  'International': 'This accommodation is for international individuals',
  'National': 'This accommodation is for national individuals',
  'Regional': 'This accommodation is for regional individuals',
  'Urban': 'This accommodation is in an urban area',
  'Suburban': 'This accommodation is in a suburban area',
  'Rural': 'This accommodation is in a rural area',
  'Coastal': 'This accommodation is in a coastal area',
  'Mountain': 'This accommodation is in a mountain area',
  'Forest': 'This accommodation is in a forest area',
  'Desert': 'This accommodation is in a desert area',
  'Tropical': 'This accommodation is in a tropical area',
  'Temperate': 'This accommodation is in a temperate area',
  'Arctic': 'This accommodation is in an arctic area',
  'Antarctic': 'This accommodation is in an antarctic area',
  'Equatorial': 'This accommodation is in an equatorial area',
  'Polar': 'This accommodation is in a polar area',
  'Mediterranean': 'This accommodation is in a Mediterranean area',
  'Continental': 'This accommodation is in a continental area',
  'Oceanic': 'This accommodation is in an oceanic area',
  'Maritime': 'This accommodation is in a maritime area',
  'Alpine': 'This accommodation is in an alpine area',
  'Valley': 'This accommodation is in a valley area',
  'Plateau': 'This accommodation is in a plateau area',
  'Plain': 'This accommodation is in a plain area',
  'Hill': 'This accommodation is in a hill area',
  'Mesa': 'This accommodation is in a mesa area',
  'Canyon': 'This accommodation is in a canyon area',
  'Gorge': 'This accommodation is in a gorge area',
  'Ravine': 'This accommodation is in a ravine area',
  'Cliff': 'This accommodation is in a cliff area',
  'Bluff': 'This accommodation is in a bluff area',
  'Ridge': 'This accommodation is in a ridge area',
  'Peak': 'This accommodation is in a peak area',
  'Summit': 'This accommodation is in a summit area',
  'Base': 'This accommodation is in a base area',
  'Foot': 'This accommodation is at the foot of a mountain',
  'Slope': 'This accommodation is on a slope',
  'Incline': 'This accommodation is on an incline',
  'Decline': 'This accommodation is on a decline',
  'Ascent': 'This accommodation is on an ascent',
  'Descent': 'This accommodation is on a descent',
  'Elevation': 'This accommodation is at a high elevation',
  'Altitude': 'This accommodation is at a high altitude',
  'Sea Level': 'This accommodation is at sea level',
  'Below Sea Level': 'This accommodation is below sea level',
  'Above Sea Level': 'This accommodation is above sea level',
  'Ground Level': 'This accommodation is at ground level',
  'Underground': 'This accommodation is underground',
  'Above Ground': 'This accommodation is above ground',
  'First Floor': 'This accommodation is on the first floor',
  'Second Floor': 'This accommodation is on the second floor',
  'Third Floor': 'This accommodation is on the third floor',
  'Fourth Floor': 'This accommodation is on the fourth floor',
  'Fifth Floor': 'This accommodation is on the fifth floor',
  'Top Floor': 'This accommodation is on the top floor',
  'Penthouse': 'This accommodation is a penthouse',
  'Basement': 'This accommodation is in the basement',
  'Attic': 'This accommodation is in the attic',
  'Loft': 'This accommodation is a loft',
  'Studio': 'This accommodation is a studio',
  'One Bedroom': 'This accommodation has one bedroom',
  'Two Bedroom': 'This accommodation has two bedrooms',
  'Three Bedroom': 'This accommodation has three bedrooms',
  'Four Bedroom': 'This accommodation has four bedrooms',
  'Five Bedroom': 'This accommodation has five bedrooms',
  'Six Bedroom': 'This accommodation has six bedrooms',
  'Seven Bedroom': 'This accommodation has seven bedrooms',
  'Eight Bedroom': 'This accommodation has eight bedrooms',
  'Nine Bedroom': 'This accommodation has nine bedrooms',
  'Ten Bedroom': 'This accommodation has ten bedrooms',
  'Master Bedroom': 'This accommodation has a master bedroom',
  'Guest Bedroom': 'This accommodation has a guest bedroom',
  'Children Bedroom': 'This accommodation has a children bedroom',
  'Nursery': 'This accommodation has a nursery',
  'Office': 'This accommodation has an office',
  'Study': 'This accommodation has a study',
  'Library': 'This accommodation has a library',
  'Den': 'This accommodation has a den',
  'Family Room': 'This accommodation has a family room',
  'Dining Room': 'This accommodation has a dining room',
  'Breakfast Nook': 'This accommodation has a breakfast nook',
  'Pantry': 'This accommodation has a pantry',
  'Laundry Room': 'This accommodation has a laundry room',
  'Mud Room': 'This accommodation has a mud room',
  'Foyer': 'This accommodation has a foyer',
  'Hallway': 'This accommodation has a hallway',
  'Staircase': 'This accommodation has a staircase',
  'Bathroom': 'This accommodation has a bathroom',
  'Half Bath': 'This accommodation has a half bath',
  'Full Bath': 'This accommodation has a full bath',
  'Master Bath': 'This accommodation has a master bath',
  'Guest Bath': 'This accommodation has a guest bath',
  'Powder Room': 'This accommodation has a powder room',
  'Closet': 'This accommodation has a closet',
  'Walk-in Closet': 'This accommodation has a walk-in closet',
  'Linen Closet': 'This accommodation has a linen closet',
  'Coat Closet': 'This accommodation has a coat closet',
  'Attic Storage': 'This accommodation has attic storage',
  'Basement Storage': 'This accommodation has basement storage',
  'Garage': 'This accommodation has a garage',
  'Carport': 'This accommodation has a carport',
  'Driveway': 'This accommodation has a driveway',
  'Parking': 'This accommodation has parking',
  'Street Parking': 'This accommodation has street parking',
  'Off-street Parking': 'This accommodation has off-street parking',
  'Covered Parking': 'This accommodation has covered parking',
  'Uncovered Parking': 'This accommodation has uncovered parking',
  'Reserved Parking': 'This accommodation has reserved parking',
  'Guest Parking': 'This accommodation has guest parking',
  'Visitor Parking': 'This accommodation has visitor parking',
  'Handicap Parking': 'This accommodation has handicap parking',
  'Electric Vehicle Charging': 'This accommodation has electric vehicle charging',
  'Tesla Charging': 'This accommodation has Tesla charging',
  'Level 1 Charging': 'This accommodation has Level 1 charging',
  'Level 2 Charging': 'This accommodation has Level 2 charging',
  'Level 3 Charging': 'This accommodation has Level 3 charging',
  'DC Fast Charging': 'This accommodation has DC fast charging',
  'Supercharger': 'This accommodation has a Supercharger',
  'Destination Charger': 'This accommodation has a destination charger',
  'Wall Connector': 'This accommodation has a wall connector',
  'Mobile Connector': 'This accommodation has a mobile connector',
  'Corded Mobile Connector': 'This accommodation has a corded mobile connector',
  'Cordless Mobile Connector': 'This accommodation has a cordless mobile connector',
  'Universal Mobile Connector': 'This accommodation has a universal mobile connector',
  'J1772 Connector': 'This accommodation has a J1772 connector',
  'CHAdeMO Connector': 'This accommodation has a CHAdeMO connector',
  'CCS Connector': 'This accommodation has a CCS connector',
  'Type 1 Connector': 'This accommodation has a Type 1 connector',
  'Type 2 Connector': 'This accommodation has a Type 2 connector',
  'Type 3 Connector': 'This accommodation has a Type 3 connector',
  'Schuko Connector': 'This accommodation has a Schuko connector',
  'CEE 7/4 Connector': 'This accommodation has a CEE 7/4 connector',
  'CEE 7/7 Connector': 'This accommodation has a CEE 7/7 connector',
  'CEE 7/16 Connector': 'This accommodation has a CEE 7/16 connector',
  'CEE 7/17 Connector': 'This accommodation has a CEE 7/17 connector',
  'CEE 7/21 Connector': 'This accommodation has a CEE 7/21 connector',
  'CEE 7/22 Connector': 'This accommodation has a CEE 7/22 connector',
  'CEE 7/23 Connector': 'This accommodation has a CEE 7/23 connector',
  'CEE 7/24 Connector': 'This accommodation has a CEE 7/24 connector',
  'CEE 7/25 Connector': 'This accommodation has a CEE 7/25 connector',
  'CEE 7/26 Connector': 'This accommodation has a CEE 7/26 connector',
  'CEE 7/27 Connector': 'This accommodation has a CEE 7/27 connector',
  'CEE 7/28 Connector': 'This accommodation has a CEE 7/28 connector',
  'CEE 7/29 Connector': 'This accommodation has a CEE 7/29 connector',
  'CEE 7/30 Connector': 'This accommodation has a CEE 7/30 connector',
  'CEE 7/31 Connector': 'This accommodation has a CEE 7/31 connector',
  'CEE 7/32 Connector': 'This accommodation has a CEE 7/32 connector',
  'CEE 7/33 Connector': 'This accommodation has a CEE 7/33 connector',
  'CEE 7/34 Connector': 'This accommodation has a CEE 7/34 connector',
  'CEE 7/35 Connector': 'This accommodation has a CEE 7/35 connector',
  'CEE 7/36 Connector': 'This accommodation has a CEE 7/36 connector',
  'CEE 7/37 Connector': 'This accommodation has a CEE 7/37 connector',
  'CEE 7/38 Connector': 'This accommodation has a CEE 7/38 connector',
  'CEE 7/39 Connector': 'This accommodation has a CEE 7/39 connector',
  'CEE 7/40 Connector': 'This accommodation has a CEE 7/40 connector',
  'CEE 7/41 Connector': 'This accommodation has a CEE 7/41 connector',
  'CEE 7/42 Connector': 'This accommodation has a CEE 7/42 connector',
  'CEE 7/43 Connector': 'This accommodation has a CEE 7/43 connector',
  'CEE 7/44 Connector': 'This accommodation has a CEE 7/44 connector',
  'CEE 7/45 Connector': 'This accommodation has a CEE 7/45 connector',
  'CEE 7/46 Connector': 'This accommodation has a CEE 7/46 connector',
  'CEE 7/47 Connector': 'This accommodation has a CEE 7/47 connector',
  'CEE 7/48 Connector': 'This accommodation has a CEE 7/48 connector',
  'CEE 7/49 Connector': 'This accommodation has a CEE 7/49 connector',
  'CEE 7/50 Connector': 'This accommodation has a CEE 7/50 connector',
  'CEE 7/51 Connector': 'This accommodation has a CEE 7/51 connector',
  'CEE 7/52 Connector': 'This accommodation has a CEE 7/52 connector',
  'CEE 7/53 Connector': 'This accommodation has a CEE 7/53 connector',
  'CEE 7/54 Connector': 'This accommodation has a CEE 7/54 connector',
  'CEE 7/55 Connector': 'This accommodation has a CEE 7/55 connector',
  'CEE 7/56 Connector': 'This accommodation has a CEE 7/56 connector',
  'CEE 7/57 Connector': 'This accommodation has a CEE 7/57 connector',
  'CEE 7/58 Connector': 'This accommodation has a CEE 7/58 connector',
  'CEE 7/59 Connector': 'This accommodation has a CEE 7/59 connector',
  'CEE 7/60 Connector': 'This accommodation has a CEE 7/60 connector',
  'CEE 7/61 Connector': 'This accommodation has a CEE 7/61 connector',
  'CEE 7/62 Connector': 'This accommodation has a CEE 7/62 connector',
  'CEE 7/63 Connector': 'This accommodation has a CEE 7/63 connector',
  'CEE 7/64 Connector': 'This accommodation has a CEE 7/64 connector',
  'CEE 7/65 Connector': 'This accommodation has a CEE 7/65 connector',
  'CEE 7/66 Connector': 'This accommodation has a CEE 7/66 connector',
  'CEE 7/67 Connector': 'This accommodation has a CEE 7/67 connector',
  'CEE 7/68 Connector': 'This accommodation has a CEE 7/68 connector',
  'CEE 7/69 Connector': 'This accommodation has a CEE 7/69 connector',
  'CEE 7/70 Connector': 'This accommodation has a CEE 7/70 connector',
  'CEE 7/71 Connector': 'This accommodation has a CEE 7/71 connector',
  'CEE 7/72 Connector': 'This accommodation has a CEE 7/72 connector',
  'CEE 7/73 Connector': 'This accommodation has a CEE 7/73 connector',
  'CEE 7/74 Connector': 'This accommodation has a CEE 7/74 connector',
  'CEE 7/75 Connector': 'This accommodation has a CEE 7/75 connector',
  'CEE 7/76 Connector': 'This accommodation has a CEE 7/76 connector',
  'CEE 7/77 Connector': 'This accommodation has a CEE 7/77 connector',
  'CEE 7/78 Connector': 'This accommodation has a CEE 7/78 connector',
  'CEE 7/79 Connector': 'This accommodation has a CEE 7/79 connector',
  'CEE 7/80 Connector': 'This accommodation has a CEE 7/80 connector',
  'CEE 7/81 Connector': 'This accommodation has a CEE 7/81 connector',
  'CEE 7/82 Connector': 'This accommodation has a CEE 7/82 connector',
  'CEE 7/83 Connector': 'This accommodation has a CEE 7/83 connector',
  'CEE 7/84 Connector': 'This accommodation has a CEE 7/84 connector',
  'CEE 7/85 Connector': 'This accommodation has a CEE 7/85 connector',
  'CEE 7/86 Connector': 'This accommodation has a CEE 7/86 connector',
  'CEE 7/87 Connector': 'This accommodation has a CEE 7/87 connector',
  'CEE 7/88 Connector': 'This accommodation has a CEE 7/88 connector',
  'CEE 7/89 Connector': 'This accommodation has a CEE 7/89 connector',
  'CEE 7/90 Connector': 'This accommodation has a CEE 7/90 connector',
  'CEE 7/91 Connector': 'This accommodation has a CEE 7/91 connector',
  'CEE 7/92 Connector': 'This accommodation has a CEE 7/92 connector',
  'CEE 7/93 Connector': 'This accommodation has a CEE 7/93 connector',
  'CEE 7/94 Connector': 'This accommodation has a CEE 7/94 connector',
  'CEE 7/95 Connector': 'This accommodation has a CEE 7/95 connector',
  'CEE 7/96 Connector': 'This accommodation has a CEE 7/96 connector',
  'CEE 7/97 Connector': 'This accommodation has a CEE 7/97 connector',
  'CEE 7/98 Connector': 'This accommodation has a CEE 7/98 connector',
  'CEE 7/99 Connector': 'This accommodation has a CEE 7/99 connector',
  'CEE 7/100 Connector': 'This accommodation has a CEE 7/100 connector'
};

// Function to get tag description
export const getTagDescription = (tag: string): string => {
  const normalizedTag = tag.trim();
  return tagDescriptions[normalizedTag] || `This accommodation has the feature: ${normalizedTag}`;
};

// Function to get tag description with fallback
export const getTagDescriptionWithFallback = (tag: string): string => {
  const description = getTagDescription(tag);
  return description || `This accommodation includes: ${tag}`;
};
